### ISSUE TITLE
Howto initiate the via PHP

### ISSUE THREAD

**Issue by gusmax777** [pimoroni/clean-shutdown#16]
Hi. 

Is there any way to initiate the clean shutdown via the console or a python or PHP script? I have a project on my Pi that has his own shutdown button in the Webgui. If I use the built in button in the gui the Pi shuts down but without ending in a clean state. 

Cheers, Thomas

**Comment by Gadgetoid** [comment]
There's no real reason for "clean-shutdown" to be involved at all if you're using another programming language to trigger a shutdown.

PHP, for example, should just be able to shell-exec a `sudo shutdown -h now` command and - while in many programming applications such an approach would be frowned upon - it might just well do the trick in your case.
