### ISSUE TITLE
Play Sound before Shutdown

### ISSUE THREAD

**Issue by marcOSS040** [pimoroni/clean-shutdown#17]
Is it possible to play a sound when the script is triggered to shut down the pi?

**Comment by Gadgetoid** [comment]
This is supported natively by Linux (systemd) so you can just drop a script into `/lib/systemd/system-shutdown/` and it will be run before shutdown/reboot. See: https://www.freedesktop.org/software/systemd/man/systemd-halt.service.html

If your script looks at the one argument its passed you can also check for `halt`, `poweroff` or `reboot` to see what's actually happening and react accordingly.

**Comment by hannesa2** [comment]
When I want to send me a warning eg, on some voltage or time before, how can I do this. Or where is the best place to do it ?
