### ISSUE TITLE
Start up using pins ( from another pi)

### ISSUE THREAD

**Issue by bortek** [pimoroni/clean-shutdown#18]
I understand that OnOffShim can be used to cut the power off but is there a way to start up pi using Pins and not a buttom? My intention is to use another pay to control "main" pi both cutting power and starting it up (cold reset).

**Comment by Gadgetoid** [comment]
There's no reason why this couldn't work- the + and - terminals for an external button on OnOff SHIM are merely the power button signal and Ground. Tie the - to Ground on your controlling Pi, and the + to a spare GPIO pin and pulling that pin LOW should have exactly the same result as a button press.

**Comment by bortek** [comment]
OK that sounds like it could work. Need to get the board and test it. 

Do I need any resistors between spare GPIO and + or can I connect it directly ?

**Comment by Gadgetoid** [comment]
Looks like the power button + terminal is pulled up to the +5v pin so a 2k Ohm resistor between the + line and Ground (ergo a 2k resistor across the + and - terminals of the button)  should be added to protect your Pi's GPIO pin. You could use 1.8k in a pinch.

I might have to grab an OnOff SHIM and test this, though!

**Comment by bortek** [comment]
Would be good if you could test and add some pics :)

**Comment by Gadgetoid** [comment]
I'm not having much luck getting it to work via the power button contacts- the latching switch used on the OnOff SHIM can be a little finickity. I suspect you'd need either a transistor or a relay, at which point the OnOff SHIM starts to become a little redundant.

For example the relays on Automation HAT are good for 2A so they could switch the power to another Pi directly and completely at will.

A Darlington Array should work, too. 

My setup is frustratingly weird because my HDMI display keeps back-powering the Pi! *grumble*

**Comment by bortek** [comment]
Thanks for testing. Automation HAT would still be more expansive and bulky than OnOffShim and a transistor. I would love to lab with it but my local store is out of stock. Need to wait for some time before I can get it and will report the progress.

**Comment by bortek** [comment]
Is there any schematic available for this board ?

**Comment by Gadgetoid** [comment]
We don't publish them (because we need to spend the time cleaning them up) but here's a screengrab:

![onoff-shim-schematic](https://user-images.githubusercontent.com/1746967/51612494-7a6b3300-1f19-11e9-8e03-e7aa7677ebba.png)

**Comment by bortek** [comment]
Thanks for the screen shot. I received my shim yesterday and will be labbi g in weekend!

**Comment by bortek** [comment]
An update. All is good. :) I have managed to get it working with shim just as I wanted it to work.

I can turn on and off Pi2 using Pi1. Done by sending high or low signal from Pi1 to Shim using GPIO4 which turns on or off Pi2. I have cross connected GND between Pi1, Pi2 and shim. 5V is connected to Pi2. I never needed to use the buttons.

**Comment by bortek** [comment]
For the benefit to the community I am updating the docs and will soon make a PR. I made a drawing of OnOffShim Fritzing and will submit it the parts DB shortly. 

Closing this Issue now.

**Comment by bortek** [comment]
Can @Gadgetoid or someone else take a look at this PR https://github.com/pimoroni/clean-shutdown/pull/20 ?

**Comment by yuergen** [comment]
> I made a drawing of OnOffShim Fritzing and will submit it the parts DB shortly.

Do you have a link to the part? I cannot seem to find it. Thank you! :)
