### ISSUE TITLE
Disabling cleanshutd cannot be commented out

### ISSUE THREAD

**Issue by ferrix** [pimoroni/clean-shutdown#19]
Due to the way the disable flag is detected, commenting it out (in instructions for example), will still disable the daemon.

https://github.com/pimoroni/clean-shutdown/blob/8dde2824019674b75b208887c198ad80f01aa4a9/daemon/usr/bin/cleanshutd#L22

**Comment by Gadgetoid** [comment]
Good spot, thanks for pointing it out. Looks like I should look into testing and merging #15 which appears to fix this issue.

**Comment by Gadgetoid** [comment]
Fixed in #15 - thank you all!
