### ISSUE TITLE
one line installer not working

### ISSUE THREAD

**Issue by kidkill** [pimoroni/clean-shutdown#23]
When I try to run (curl https://get.pimoroni.com/cleanshutdown | bash) , I get an error saying 

> Checking environment...
We can't connect to the Internet, check your network!

I definitely have an internet connection. Any help would be appreciated.

**Comment by Gadgetoid** [comment]
This is a quirk in our connectivity check- we're pinging (last I knew) Google's DNS servers to verify an internet connection. Honeslty I think we just need to drop this check altogether and check exit codes for connection failures. It's been on my TODO list for a while.

**Comment by Gadgetoid** [comment]
Have opened https://github.com/pimoroni/get/issues/202 to track this, since it applies across all of our "get" scripts.
