### ISSUE TITLE
Prevent button trigger during start / shutdown?

### ISSUE THREAD

**Issue by chriwen** [pimoroni/clean-shutdown#24]
I would like to ask how I can disable the button trigger once it was fired for an certain amount of time (e.g. 10 seconds). 
Use case: Having the on/off shim implemented in a music for kids. sometimes they double tap on the button and in some cases the whole system crash. So I want to prevent that the button triggers any action once it was fired.

Thank you for any hints an tips.

farbschein

**Comment by Gadgetoid** [comment]
Good question- the shutdown script is written in bash, so it's not the friendliest thing to reason about and change. I may not have an answer anytime soon.
