### ISSUE TITLE
Busy looping

### ISSUE THREAD

**Issue by campag** [pimoroni/clean-shutdown#5]
Ref https://github.com/pimoroni/clean-shutdown/blob/master/daemon/usr/bin/cleanshutd#L99

Looks like that **sleep $polling_rate** should be in the outer **while** loop. CPU usage plummets when I move it one line below.

Regards David.

**Comment by Gadgetoid** [comment]
Looks like you're right- where it is now it wouldn't have any effect unless the button is pressed.

**Comment by RogueM** [comment]
ha! fixed!
